version: '3'

services:
  app:
    image: my-web-app
    build: .
    ports:
      - "3000:3000"
    networks:
      - webnet
    container_name: my-web-app-container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    restart: always

networks:
  webnet:
    driver: bridge
